# Generated by Django 3.0.9 on 2020-08-19 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20200817_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_seeker_profile',
            name='age',
        ),
        migrations.AddField(
            model_name='job_seeker_profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
