# Generated by Django 3.0.9 on 2020-08-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20200819_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_profile',
            name='mobile_number',
            field=models.CharField(max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='company_profile',
            name='phone_number',
            field=models.CharField(max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='job_seeker_profile',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='job_seeker_profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
    ]
