# Generated by Django 3.0.9 on 2020-08-24 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20200819_2047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_seeker_profile',
            old_name='country_of_residence',
            new_name='nationality',
        ),
    ]
