# Generated by Django 3.0.9 on 2020-08-25 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_company_profile_mobsile_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_profile',
            name='mobsile_number',
        ),
    ]
