# Generated by Django 3.0.9 on 2020-08-25 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact',
        ),
    ]
