# Generated by Django 3.0.9 on 2020-08-26 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='ContactUs',
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name_plural': 'Users Messages'},
        ),
    ]
